all:
	g++ problem1.c -o problem1.o
	g++ problem2.c -o problem2.o
	g++ problem3.c -o problem3.o
	g++ problem4.c -o problem4.o
	g++ problem5.c -o problem5.o
	g++ problem6.c -o problem6.o
	g++ problem7.c -o problem7.o
	g++ problem8.c -o problem8.o
	g++ problem9.c -o problem9.o
	g++ problem10.c -o problem10.o
	g++ problem11.c -o problem11.o
	g++ problem12.c -o problem12.o
	g++ problem13.c -o problem13.o
	g++ problem14.c -o problem14.o

remove:
	rm -rf problem1.o
	rm -rf problem2.o
	rm -rf problem3.o
	rm -rf problem4.o
	rm -rf problem5.o
	rm -rf problem6.o
	rm -rf problem7.o
	rm -rf problem8.o
	rm -rf problem9.o
	rm -rf problem10.o
	rm -rf problem11.o
	rm -rf problem12.o
	rm -rf problem13.o
	rm -rf problem13.o
	rm -rf problem14.o
