all:
	g++ Problem1.c -o Problem1.o
	g++ Problem2.c -o Problem2.o
	g++ Problem3.c -o Problem3.o
	g++ Problem4.c -o Problem4.o
	g++ Problem5.c -o Problem5.o
	g++ Problem6.c -o Problem6.o
	g++ Problem7.c -o Problem7.o
	g++ Problem8.c -o Problem8.o
	g++ Problem9.c -o Problem9.o
	g++ Problem10.c -o Problem10.o
	g++ Problem11.c -o Problem11.o
	g++ Problem12.c -o Problem12.o
	g++ Problem13.c -o Problem13.o
	g++ Problem14.c -o Problem14.o
